# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hvolume2d_Rcpp <- function(S, x1, x2) {
    .Call(`_GPareto_hvolume2d_Rcpp`, S, x1, x2)
}

exipsi_Rcpp <- function(a, b, m, s) {
    .Call(`_GPareto_exipsi_Rcpp`, a, b, m, s)
}

EHI_2d_wrap_Rcpp <- function(P, r, mu, s) {
    .Call(`_GPareto_EHI_2d_wrap_Rcpp`, P, r, mu, s)
}

